### ISSUE TITLE
Help: How to use vinyl-paths in gulpfile.js to avoid [ERR_REQUIRE_ESM]?

### ISSUE THREAD

**Issue by SamuelMiller** [sindresorhus/vinyl-paths#12]
I am getting "Error [ERR_REQUIRE_ESM]: require() of ES Module" error when I do the following in my gulpfile.js, following older tutorials online:

```
const gulp =
    { src, dest, watch, series, parallel } = require('gulp'),
    $ = require('gulp-load-plugins')({ camelize: true, lazy: true }),
    del = require('del'),
    vinylPaths = require('vinyl-paths')
};

function convertCase() {
    return src(['./src/assets/fonts/playtime/*.ttf'])
        .pipe(vinylPaths(del))
        .pipe($.rename(function (path) {
            path.dirname = path.dirname.toLowerCase(); path.basename = path.basename.toLowerCase(); path.extname = path.extname.toLowerCase();
        }))
        .pipe(dest('./src/assets/fonts'))
};
```
I suspect the error is occurring because vinyl paths is now an ESM module. Reading online, I seem to have three options:

Switch the project to an ESM module, dynamically import an ESM module into a CommonJS module using let, await, import, or use an older version of the plugin. Besides downgrading the vinyl-plugin , I am using, I have absolutely no idea how to do the other options--what does using an ESM module look like in gulpfile.js?  Is there a way, I can use vinyl-paths using a somewhat similar format to the above, so I can use my other gulp plugins in my gulpfile.js?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
