### ISSUE TITLE
I wonder how to easily restore vinyl-paths after its changed

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/vinyl-paths#2]
https://github.com/wearefractal/vinyl-fs/issues/76
After `gulp.dest('dist')`, `cwd`, `base`, and `path` will be overwritten to match the folder. I wonder if there is an easy way to restore them?

Maybe something like this?
```js
gulp.task('delete2', function (cb) {
    var vp = vinylPaths();

    gulp.src('app/*')
        .pipe(vp)
        .pipe(gulp.dest('dist'))
        .pipe(vp.restore())
        .pipe(...);
});
```
Or should it go to another plugin? Since this module is called `vinyl-paths` I open the issue here.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/gulp-revert-path ?

**Comment by stevemao** [comment]
oh yay :+1:

**Comment by stevemao** [comment]
I knew this already existed (just didn't find it). But since the module name `vinyl-paths` I was thinking it should probably be able to do more with the `paths`

**Comment by sindresorhus** [comment]
@stevemao https://github.com/sindresorhus/vinyl-paths/commit/b694eeff942c74de10dab52240946f904be4b502

**Comment by stevemao** [comment]
Oh that module can only revert to the previous path. 
would be great if something can do.

```
gulp.src('app/*')
        .pipe(storePath())
        .pipe(gulp.dest('dist'))
        .pipe(gulp.dest('dist2'))
        .pipe(storePath.restore())
        .pipe(...);
```

**Comment by sindresorhus** [comment]
It wouldn't know how many `gulp.dest` you've used, but I could add support for passing a number of reversions to the method.

```js
gulp.src('app/*')
        .pipe(storePath())
        .pipe(gulp.dest('dist'))
        .pipe(gulp.dest('dist2'))
        .pipe(storePath.restore(2))
        .pipe(...);
```

Open an issue or even better a PR, on https://github.com/sindresorhus/gulp-revert-path.

**Comment by stevemao** [comment]
Will do :D
