### ISSUE TITLE
Issue trying to force using outside directory

### ISSUE THREAD

**Issue by landed1** [sindresorhus/vinyl-paths#4]
.pipe(vinylPaths(del(DEST, { force: true })))

I get an error in the vinyls code here I need force to work on directory outside of the root....
ty

**Comment by sindresorhus** [comment]
That has nothing to do with this module, but rather `del`.

**Comment by landed1** [comment]
it doesn't accept the correct del syntax.

**Comment by bduff9** [comment]
While @sindresorhus provided the technically correct answer, it was also terrible from a support standpoint :-)

For @landed1 or anyone else who might find this like I did while searching, you just have to provide a promise returning function to vinyl-paths (which from my understanding, del is), so as a work-around using arrow functions, the following works for my needs:

```
gulp.src(someSrc)
  .pipe(vinylPaths(paths => del(paths, { force: true })))
  .pipe(doSomethingElse);
```

Hope it helps!
