### ISSUE TITLE
It seems like v3.0.0 breaks my build

### ISSUE THREAD

**Issue by pepelsbey** [sindresorhus/vinyl-paths#7]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2430%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/vinyl-paths/issues/7)

After updating vinyl-paths to v3.0.0 my build is broken. Rolling back to 2.1.0 helps. Please let me know if I can help investigating it further. Meanwhile, here’s what I got for now:

With `"vinyl-paths": "^2.1.0"` in my package.json:

<details>
<summary>npx gulp cache:hash</summary>

```
[12:14:09] Using gulpfile ~/Documents/Веб-стандарты/Код/wsd.events/gulpfile.js
[12:14:09] Starting 'cache:hash'...
[12:14:09] Finished 'cache:hash' after 17 ms
```

</details>

With `"vinyl-paths": "^3.0.0"`:

<details>
<summary>npx gulp cache:hash</summary>

```
[12:13:24] Using gulpfile ~/Documents/Веб-стандарты/Код/wsd.events/gulpfile.js
[12:13:24] Starting 'cache:hash'...
[12:13:24] 'cache:hash' errored after 43 ms
[12:13:24] Error: write callback called multiple times
    at afterTransform (/Users/pepelsbey/Documents/Веб-стандарты/Код/wsd.events/node_modules/readable-stream/lib/_stream_transform.js:96:33)
    at TransformState.afterTransform (/Users/pepelsbey/Documents/Веб-стандарты/Код/wsd.events/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /Users/pepelsbey/Documents/Веб-стандарты/Код/wsd.events/node_modules/vinyl-paths/index.js:13:6
```

</details>

Here’s the part of the gulpfile.js that breaks

<details>
<summary>gulpfile.js</summary>

```
const del = require('del');
const gulp = require('gulp');
const paths = require('vinyl-paths');
const rev = require('gulp-rev');

// …

gulp.task('cache:hash', () => {
	return gulp.src([
			'dest/styles/*.css',
			'dest/scripts/*.js'
		], {
			base: 'dest'
		})
		.pipe(paths(del))
		.pipe(rev())
		.pipe(gulp.dest('dest'))
		.pipe(rev.manifest())
		.pipe(gulp.dest('dest'));
});
```

</details>

And the whole package.json

<details>
<summary>package.json</summary>

```
{
  "private": true,
  "engines": {
    "node": ">=4.1"
  },
  "scripts": {
    "start": "gulp",
    "build:dev": "gulp build:dev",
    "build:prod": "gulp build:prod",
    "deploy": "gulp deploy",
    "test": "ls dest",
    "pretest": "gulp build:prod"
  },
  "dependencies": {
    "autoprefixer": "^9.0.1",
    "browser-sync": "^2.26.7",
    "del": "^5.0.0",
    "gulp": "^4.0.0",
    "gulp-csso": "^3.0.0",
    "gulp-htmlmin": "^5.0.1",
    "gulp-postcss": "^8.0.0",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^1.0.0",
    "gulp-responsive": "^2.13.0",
    "gulp-rev": "^9.0.0",
    "gulp-rev-replace": "^0.4.3",
    "gulp-rsync": "0.0.8",
    "gulp-sass": "^4.0.1",
    "gulp-uglify": "^3.0.0",
    "postcss-inline-svg": "^4.1.0",
    "require-dir": "^1.0.0",
    "sass-mq": "^5.0.0",
    "vinyl-paths": "^2.1.0"
  }
}
```
<details>

And here’s the whole repository: [web-standards-days](https://github.com/web-standards-ru/web-standards-days).

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $30.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($30.00)

### Submitted pull Requests
- [#8 Restore previous behavior, pass the vinyl object on to the callback](https://issuehunt.io/r/sindresorhus/vinyl-paths/pull/8)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/vinyl-paths/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by Mayccoll** [comment]
Any clue about this?
Same error using `.pipe(vinylPaths(del))`

**Comment by bobthekingofegypt** [comment]
I tried to have a look at this but after checking out your sample repository unfortunately I cannot recreate the issue. 

I tried -
MacOSX - node 8/10/11 all work fine on version 3.0.0.
Gentoo linux - node 11 works fine on version 3.0.0.

What system are you using?

**Comment by pepelsbey** [comment]
I have macOS 10.14.6 (it was the same on 10.14.5) and it’s still broken

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/105274/61749767-3fed3080-adac-11e9-80a3-1ed4b890da8c.png">

Here’s what I do to recreate it:

```sh
git clone git@github.com:web-standards-ru/web-standards-days.git
cd web-standards-days/
npm i
npx gulp cache:hash
[success]
npm install --save vinyl-paths@3.0.0
npx gulp cache:hash
[failure]
```

Wait… now it suddenly works. It failed 5 minutes ago and it works now. Let me test it further.

**Comment by pepelsbey** [comment]
It seems like it’s still broken on Travis

https://travis-ci.org/web-standards-ru/web-standards-days/builds/562811486

[Here’s the diff](https://github.com/web-standards-ru/web-standards-days/compare/c59ed0a35399...42fb3f94255f) that made it fail.

**Comment by bobthekingofegypt** [comment]
Strange.

Could you try turning off the travis node caching for a build?

https://docs.travis-ci.com/user/caching/#npm-cache
